services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_USER_ID=admin
      - DEFAULT_API_KEY=your_default_api_key
    depends_on:
      redis:
        condition: service_healthy

  redis:
    build: ./redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
